server:
  port: 8086
spring:
  datasource:
    url: jdbc:sqlserver://8.162.6.187:1433;databaseName=shop;encrypt=false;sendStringParametersAsUnicode=true;sendTimeAsDatetime=false;selectMethod=cursor;responseBuffering=adaptive
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: JingXuPassword123

