server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://101.42.157.163:3306/shop?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 202430904jingXu